# -*- coding: utf-8 -*-
"""LAB-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcoaauAG2U3wKfOg0d4qwklSluZFauyC
"""

# ================================
# 1. Import Required Libraries
# ================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    roc_auc_score
)

# ================================
# 2. Load Dataset
# ================================
# Ensure 'parkinsons.data' is uploaded to the Colab environment.
# If uploaded, it will typically be found in the /content/ directory.
df = pd.read_csv("/content/parkinsons.data")

print("First 5 Rows:")
print(df.head())

# ================================
# 3. Descriptive Statistics
# ================================
print("\nDataset Info:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

print("\nClass Distribution:")
print(df['status'].value_counts())

# ================================
# 4. Data Cleaning & Preprocessing
# ================================

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Drop 'name' column (not useful for prediction)
if 'name' in df.columns:
    df.drop(columns=['name'], inplace=True)

# Define features and target
X = df.drop("status", axis=1)
y = df["status"]

# ================================
# 5. Train-Test Split
# ================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ================================
# 6. Feature Scaling
# ================================
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ================================
# 7. Build Logistic Regression Model
# ================================
model = LogisticRegression(max_iter=500)
model.fit(X_train_scaled, y_train)

# ================================
# 8. Model Prediction
# ================================
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

# ================================
# 9. Model Evaluation
# ================================

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)

# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, y_prob)
print("ROC-AUC Score:", roc_auc)

# ================================
# 10. ROC Curve Plot
# ================================
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure()
plt.plot(fpr, tpr)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()

import os
print(os.listdir("/content"))

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("parkinsons.data")

# ================================
# 1. Import Required Libraries
# ================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    roc_auc_score
)

# ================================
# 2. Load Dataset
# ================================
df = pd.read_csv("parkinsons.data")

print("First 5 Rows:")
print(df.head())

# ================================
# 3. Descriptive Statistics
# ================================
print("\nDataset Info:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

print("\nClass Distribution:")
print(df['status'].value_counts())

# ================================
# 4. Data Cleaning & Preprocessing
# ================================

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Drop 'name' column (not useful for prediction)
if 'name' in df.columns:
    df.drop(columns=['name'], inplace=True)

# Define features and target
X = df.drop("status", axis=1)
y = df["status"]

# ================================
# 5. Train-Test Split
# ================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ================================
# 6. Feature Scaling
# ================================
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ================================
# 7. Build Logistic Regression Model
# ================================
model = LogisticRegression(max_iter=500)
model.fit(X_train_scaled, y_train)

# ================================
# 8. Model Prediction
# ================================
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

# ================================
# 9. Model Evaluation
# ================================

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", cm)

# Classification Report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# ROC-AUC Score
roc_auc = roc_auc_score(y_test, y_prob)
print("ROC-AUC Score:", roc_auc)

# ================================
# 10. ROC Curve Plot
# ================================
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

plt.figure()
plt.plot(fpr, tpr)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()